
# get products (index)
GET http://localhost:3000/products.json


###
# get product (show)
GET http://localhost:3000/products/12.json

###
# create product
POST http://localhost:3000/products
content-type: application/json

{
  "name": "Car",
  "price": 100,
  "image_url": "www.abc.com",
  "description": "this is a cheap car!!"
}

###
# update product
PATCH http://localhost:3000/products/4
Content-Type: application/json

{
  "name": "Airplane",
  "price": 9,
  "image_url": "www.abc.com",
  "description": "this is a cheap airplane!!"
}


###
# delete product
DELETE http://localhost:3000/products/9


### validate?
Patch http://localhost:3000/products/1
content-type: application/json

{
  "price": 100,
  "image_url": "www.abc.com",
  "description": "this is a cheap car!!"
}

###
http://localhost:3000/suppliers

###
http://localhost:3000/suppliers/1

###
http://localhost:3000/images

###
http://localhost:3000/images/1